### ISSUE TITLE
Icons not appearing

### ISSUE THREAD

**Issue by joecreighton** [joecreighton/moon-phase#1]
The math to determine which icon to use looks right (and the proper code appears in console.error) but I'm a Javascript/Coffeescript/SVG neophyte. I need to learn why this is failing.

**Comment by joecreighton** [comment]
Paging @felixhageloh to the white courtesy phone.  I can't see why it's not working so I'm hoping you can.  It's so closely based on the weather widget (the icon bits are nearly identical), I'm also hoping it's trivial for you.

At your leisure, of course.  Thanks.

**Comment by felixhageloh** [comment]
I had a quick look and tried the code, but I get either a "failed to reach USNO illumination table" or a JSON parse error

**Comment by joecreighton** [comment]
I'd like to suggest a refresh (or resave of the index.coffee file) to get it to load.  The functionality is there but I have seen the odd bit of weirdness on a first run (dropping the folder in) or after waking from sleep.

**Comment by felixhageloh** [comment]
I actually tried that several times, but it seems to alternate between the two errors. I.e. I either get an error response from the command (with { "error": "failed to reach USNO illumination table" }) or I get, what looks like, a proper response but then with invalid JSON so JSON.parse fails

**Comment by joecreighton** [comment]
(I'm new to this so if it's more appropriate to upload changes for you to download rather than have you edit them directly, let me know).

At your convenience:

Curl is defined with a timeout at the top of get-phase.sh.  Feel free to remove "--connect-timeout 5" and let that run.  I realized this might prevent the failure in Amsterdam based on my impatience in North America.

To mimic your (assumed) environment, I've made these changes locally:

```
index.coffee: city = Amsterdam
get-phase.sh: TZ="01.00"
```

And the rise/set times seem accurate (via http://www.timeanddate.com/moon/netherlands/amsterdam)

If the JSON error appears, I'd like to impose upon you to run the following from within the widgets directory; if you set your city, only the second is required; if you don't, replace `Amsterdam,,` with your city,region,country (comma separated)

```
http://freegeoip.net/csv/
https://maps.googleapis.com/maps/api/geocode/json?address=Amsterdam,,&sensor=false
```

(edited; the previous doesn't reveal what we're coming into the USNO call with).

**Comment by felixhageloh** [comment]
Thanks for the detail's, I will check this out later today or this weekend! 

[Internet's fast here btw](http://testinternetspeed.org/blog/netherlands-has-fastest-broadband-according-to-netflix/), if I understood your comment correctly ;)

**Comment by felixhageloh** [comment]
No need to upload the changes btw!

**Comment by joecreighton** [comment]
No intent to mock or disparage your bandwidth,\* just trying to rule out issues.  The graceful error means a file was not created.  Actually, that's an assumption I shouldn't make either: do you see any problem with the widget creating a temporary file within its own directory structure?  Since it works for me, I didn't think it wouldn't work for everyone else.

The invalid JSON hasn't happened to me in a while now so that's more curious.

*My home is so rural, I never mock someone's bandwidth because mine is always much, much worse.  :)

Thanks for your patience and your time.

(commands to run have been edited, above)

**Comment by felixhageloh** [comment]
No worries it was just some friendly banter and ruling out connection issues :). 
So I've singled out the JSON parse error: It was the time zone (`tz`) inside the json that was breaking. It is a number with leading zero `01.00` instead of a string (or a valid number). I quickly fixed it by changing 

```
TZ=`date +%z | sed 's/..$/.&/'`
to 
```

TZ=\"`date +%z | sed 's/..$/.&/'`\"

```

but I'm not sure if you need it to be a number further down the line.

```

**Comment by felixhageloh** [comment]
I have not found the icon issue yet, but I'll keep looking

**Comment by joecreighton** [comment]
I'll look into that.  And take your time, please: I haven't even gone through a full development cycle of moon data yet :)  (I just found my first oversight last night).

**Comment by joecreighton** [comment]
${TZ} is used further down, wrapped in braces to protect it from being mis-parsed.

I'm executing `moon-phase.widget/get-phase.sh` at the command line (optionally passing `Location "" ""` (for your favourite value of `Location` and to skip the freegeoip lookup) and it returns the JSON object to STDOUT.  When I make the same change you did here, it gives me an error:

```
ed: 1: "s/..$/.&/"": bad flag in substitute command: '"'
./gp: line 75: +%z: command not found
```

which, to me, seem like I've just broken it.  Prior to the first TZ appearance, there are other vars assigned values using the same method (back quotes around OS commands):

```
city=`echo $city | sed 's/ /%20/g'`
region=`echo $region | sed 's/ /%20/g'`
country=`echo $country | sed 's/ /%20/g'`
latlong=`echo $coords | awk -F"\"location\" :" '{ print $2 }'`
latitude=`echo $latlong | sed 's/,/ /g' | awk '{ print $4 }'`
longitude=`echo $latlong | sed 's/,/ /g' | awk '{ print $7 }'`
```

so I'm curious how you're executing things so that double quotes wrapped around the OS command are not a syntax error?

**Comment by felixhageloh** [comment]
I think the differences we are seeing are due to the fact that my time zone is positive (and thus starts with a leading `+`) whereas yours is negative. So it seems like the script did not handle those the same way. I did not spent much time finding the exact cause, but I did get things working in the end.

### time zone

First I noticed that the USNO api expects the timezone to be a simple number like `1`, `-7` or `2.0`, `-8.00` etc. It also looks like it will just spit back whatever string you provide, inside its JSON response. This is why, in my case, the script set `01.00` as the timezone and that's what I got back in the response and which is what caused the JSON parse error. I fixed it by setting the `TZ` variable like this:

``` bash
TZ=`date +%z | sed 's/..$/.&/' | sed 's/\(-\)0/\1/' | sed 's/\+0//'`
```

This will give us numbers like `-2.00`, `1.00` etc. I'm sure there is a shorter and more elegant way to do this, but I'm not so handy with bash and sed. This fixes the JSON response and you can even skip parsing of the JSON further down te like where you do

``` bash
astrodata=`echo $astrodata |\
 sed 's/"tz":\(\-*\)\(0\)\([0-9]\)\.\([0-9]\)\([0-9]\)/"tz":\"\\1\\2\\3\\4\\5"/'`
```

### icons

Now for the icons. It turns out just to be an issue with icon font. You had

```
@font-face
  font-family: 'Weather'
  src url(weather.widget/moon-icons.svg) format('svg')
```

which is probably copied from the weather widget. If you change that to

```
@font-face
  font-family: 'Weather'
  src url(moon-phase.widget/moon-icons.svg) format('svg')
```

it will work

**Comment by joecreighton** [comment]
I've learned that "+" appears for timezones East of GMT rather than just the whole number so I thank you for that bit of data.  As they say, this is probably the root cause.  I'll walk through the code with that knowledge and try to polish things up.

As for...

`src url(weather.widget/moon-icons.svg) format('svg')`

I think the appropriate response here is, "Doh!"  Can't believe that got by me. :)  That simple fix got me an icon.  I now get to play with scaling it right.

Many thanks!

**Comment by felixhageloh** [comment]
glad I could help out :)

**Comment by joecreighton** [comment]
First issue closed.  Nice!  (When I get back to it, and if warranted, the timezone stuff may get its own issue)

I'm thinking the icons have a height associated with them and their size isn't just bound to their shapes (which makes sense for a font: same baseline, middle alignment, etc.)

![screen shot 2016-03-15 at 10 50 04](https://cloud.githubusercontent.com/assets/17548684/13784331/d7069226-ea9c-11e5-9c99-fc595ae7a3c1.png)

So I'm hacking around with relative positioning and overlap, which works pretty well even when scaling up the font size.  I'm hoping this is a reasonable solution.

![screen shot 2016-03-15 at 10 45 17](https://cloud.githubusercontent.com/assets/17548684/13784334/da603bde-ea9c-11e5-9970-a2dc035b619e.png)

Getting my desired effects of a background to the moon icon and a background to the visible elements of the widget will be an interesting challenge for this CSS newbie.

**Comment by joecreighton** [comment]
> I had a quick look and tried the code, but I get either a "failed to reach USNO illumination table" or a JSON parse error

I really, really hope you had this widget running in both monitors :)  Using the PID to name a temporary file fixed that at my end.

**Comment by felixhageloh** [comment]
no it turned out that I named the widget folder differently (I downloaded individual widget files directly from github instead of downloading the zip to make sure i had the latest version) - so no worries :)
